language: php
php:
  - 7.3
  - 7.4
  - 8.0
os: linux
before_script: 
  - cd evadus-social-master
  - cp .env.example .env
  - composer update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  #- php artisan serve
before_install:
  - mysql -e 'CREATE DATABASE evadus;'
script:
  - vendor/bin/phpunit
services:
  - mysql
